[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/orzephyrous/"

[social.params]
icon = "brand-github"

[[social]]
identifier = "bangumi"
name = "bangumi"
url = "https://bgm.tv/user/orzephyr"

[social.params]
icon = "brand-bilibili"

[[social]]
identifier = "mail"
name = "Mail"
url = "mailto:1416385800@qq.com"

[social.params]
icon = "mail"
