[sidebar]
subtitle = "Random personal blog. 随机刷新的个人博客orz (Under construction...)"

[sidebar.avtar]
enabled = true
local = true
src = "img/avatar.png"

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

[[widgets.page]]
type = "toc"
