favicon = "favicon.png"

[sidebar]
subtitle = "Random personal blog. 随机刷新的个人博客orz (Under construction...)"

[sidebar.avtar]
enabled = true
local = true
src = "img/avatar.png"

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

[widgets]
homepage = [
    {type = "search"},
    # {type = "archives"},
    {type = "tag-cloud"},
]
page = [{type = "toc"}]

[footer]
since = 2026
customText = "orz"

